import { Inter } from "next/font/google";
import "./globals.css";
import styles from "@/app/page.module.css";

const inter = Inter({ subsets: ["latin"] });
import AsideTop from "./Components/CommanComp/AsideTop";
import CreateGroup from "./Components/CommanComp/CreateGroup";
import GroupLists from "./Components/CommanComp/GroupLists";
import MyGroups from "./Components/CommanComp/MyGroups";
import AutoLogin from "./Components/CommanComp/AutoLogin";



import CheckloginStates from '../../context/auth/CheckloginStates'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <CheckloginStates >
          <div className={styles.Fullbg}>
            <div className={styles.Container}>
              <div className={styles.ChatSection}>
                <div className={styles.ChatSectionA}>
                  <AutoLogin />
                  <AsideTop />
                  {/* <CreateGroup /> */}
                  <MyGroups />
                 
                  {/* <GroupLists /> */}

                </div>
                <div className={styles.ChatSectionB}>
                  {children}
                  <div className={styles.FooterDevider}></div>
                </div>
              </div>
            </div>
          </div>
        </CheckloginStates >
      </body>
    </html>
  );
}
